

CREATE DATABASE "DBA"
    WITH
    OWNER = dbadmin
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	

GRANT TEMPORARY, CONNECT ON DATABASE "DBA" TO PUBLIC;

GRANT ALL ON DATABASE "DBA" TO dba_team WITH GRANT OPTION;

GRANT ALL ON DATABASE "DBA" TO dbadmin;
